FROM golang:1.7@sha256:9bd56cd1d298b30e79e6f6ea14405c98b6cfb6553e05d2cd8ac02ecfc544dee0

RUN go get github.com/mitchellh/gox

ENV CGO_ENABLED=0

COPY main.go     /go/src/github.com/realestate-com-au/dfresh/
COPY vendor.conf /go/src/github.com/realestate-com-au/dfresh/

COPY cmd      /go/src/github.com/realestate-com-au/dfresh/cmd
COPY registry /go/src/github.com/realestate-com-au/dfresh/registry
COPY vendor   /go/src/github.com/realestate-com-au/dfresh/vendor

WORKDIR /go/src/github.com/realestate-com-au/dfresh

RUN gox -osarch "linux/amd64 darwin/amd64"
