#!/bin/bash -e

cd $(dirname $0)/..

docker build -f Dockerfile.xcompile .
xcompile_image=$(docker build -f Dockerfile.xcompile -q .)

mkdir -p target
docker run --rm $xcompile_image sh -c 'tar cf - dfresh_*' | (cd target && tar xvf -)

docker build -t cowbell/dfresh:latest .
